### ISSUE TITLE
Stacking tanks of different types doesn't update side texture

### ISSUE THREAD

**Issue by Indemnity83** [Indemnity83/irontank#14]
When you stack BuildCraft tanks, the side texture changes so that the bottom line of the upper tanks doesn't show. 

This works fine for any of the extended tanks when stacking with themselves, but when you mix any various tanks together the side texture is not updated as expected.

**Comment by Indemnity83** [comment]
After some brief investigation, this is a problem with the logic in the BuildCraft BlockTank class that's being extended. BuildCraft/BuildCraft#3047 initiated and accepted by the BuildCraft team should resolve this in the next release of BuildCraft. I'm leaving this issue open until the patch is released.

**Comment by asiekierka** [comment]
There are tons of things in BuildCraft I or the previous developers hadn't thought of, admittedly. It's a giant codebase where nobody is 100% sure of what is going on everywhere, sadly.

**Comment by Indemnity83** [comment]
Oh certainly; I'm not trying to take anything away from the BuildCraft code, its wasn't ever designed to be extended like this I'm sure. But thats the beauty of open source :+1:

**Comment by asiekierka** [comment]
Yes! Yes it is! Generally, I'm trying to make BuildCraft more extensible as I go.

**Comment by asiekierka** [comment]
Pushed in BC 7.1.6.
