### ISSUE TITLE
Implement a tank feature system

### ISSUE THREAD

**Issue by Indemnity83** [Indemnity83/irontank#23]
Maybe this goes too far outside the intentions of BuildCraft (which I'd kinda like to stick to) but my original inspiration for extending the tank from BuildCraft was to create an "autarchic tank" which would auto pull liquids from nearby machines. 

More useful than specific speciality tanks would be the ability to add feature modules to the tanks that would add things like the autarchic behavior. 

The first step however, is to implement an events system for tanks, and an interface for the modules. That is the purpose of this enhancement. 

I welcome feedback and discussion.

**Comment by Sempiternity87** [comment]
Do you want this as another mod, or implemented into the base Iron Tanks mod?

**Comment by Indemnity83** [comment]
Would probably have to be done as part of IronTanks; can't imagine trying to do it as another mod since this mod doesn't have an API.

**Comment by Indemnity83** [comment]
This isn't really on the table anymore.
