### ISSUE TITLE
Add Void Tank

### ISSUE THREAD

**Issue by Indemnity83** [Indemnity83/irontank#24]
similar to the boot chest from rail craft, or the void pipe from buildcraft. Sometimes you just want to destroy all the things, including liquids!

Recipe would be a buildcraft tank with red stone and ink sac.

This does not provide any new functionality, just an aesthetically different way to achieve fluid deletion.

**Comment by Indemnity83** [comment]
Reminder to self, the void pipe may not instantly delete items ... make sure the tank acts similarly.

**Comment by Sempiternity87** [comment]
What about having an upgrade that allows the tank to be filled up to the max, then voids any extra?

**Comment by Indemnity83** [comment]
One of the folks on the BuildCraft discord suggested a tank with the same function; I like the idea of implementing it as a module as part of #23
