### ISSUE TITLE
Tanks not fill more >32Mb at the chunks border.

### ISSUE THREAD

**Issue by Ghostlyr** [Indemnity83/irontank#28]
Have found a significant bug with all tanks from addon when its located at the chunks border - they not filling more 32MB.

No any errors on logs.

**Steps to reproduce:**
1. Place any iron tank at the chunk border (i have marked it with cobblestone)
2. Fill with more 32MB any fluid
3. Unload this chunk or re-join to game and fill one more bucket.
4. Unload chunk or reload worn again and be perplexed happens: block shows what it fully filled, but really you cant take away more 32 MB and it Waila shows is not filled more.

![2016-03-21_13 02 03](https://cloud.githubusercontent.com/assets/8511068/13912332/0a73f590-ef66-11e5-966a-276c64b5dc12.png)
After reloading world:
![2016-03-21_13 02 19](https://cloud.githubusercontent.com/assets/8511068/13912460/88619d1c-ef67-11e5-99b0-499c2ae4b6d7.png)

**Product Versions**
MC 1.7.10 Forge 1614.
Buildcraft 7.1.16.
IronTanks 1.0.1.50

**Other installed mods:** industrialcraft, ironchest, NEI, codechickencore, Waila. All updated to lastest versions.

**Comment by Indemnity83** [comment]
Very interesting; so you're saying if you put another tank off the border and filled it then reloaded this doesn't happen? I'm not sure why/how the chunk border is messing with the tank.

I haven't tried with the version of forge you're using either so there may be something there too.

**Comment by Indemnity83** [comment]
The fact that the tank shows full when it's not is probably the real bug; reloading just reloads the item data and forge is pretty good about cleaning up junk data (like a liquid container with more than its max).

**Comment by Ghostlyr** [comment]
Yes, am I unable to reproduce the problem off the chunk border. And after such bug tank loses the ability to be filled - bucket anyway remains in the hand, indicators show that filling does, but after one more world reloading tank fullness goes back to 32 MB.

**Comment by Ghostlyr** [comment]
Oh, no... I tried to look more closely and sometimes it's happens and out of chunk bounds...
I don't understand what is happening. Some fine keep their state, and some do not. Some of them even lose their state when filled less than 32 MB. On the border chunks i lost all that I checked.

![b](https://cloud.githubusercontent.com/assets/8511068/13934201/0307de00-efdb-11e5-9155-e0f2ac8a4eeb.png)
![a](https://cloud.githubusercontent.com/assets/8511068/13934198/fedc0ce8-efda-11e5-9647-693dc6aef908.png)

**Comment by Indemnity83** [comment]
I'm unable to test right now; could be able to tonight but is it possible to roll back to forge 10.13.4.1448 to see if it still happens. That's the version that IronTank was built against. 

Also, any other mods loaded besides Buildcraft? Just have to ask.

**Comment by Ghostlyr** [comment]
I tried to test with 1448 and use only these mods:

![4564545656456456](https://cloud.githubusercontent.com/assets/8511068/13944508/03f134d8-f030-11e5-80c2-96746681f41d.png)

Identical results:

![2016-03-22_13 17 43](https://cloud.githubusercontent.com/assets/8511068/13944593/8d4b3544-f030-11e5-8419-6b90248eb613.png)

![2016-03-22_13 17 52](https://cloud.githubusercontent.com/assets/8511068/13944595/904d43a4-f030-11e5-992b-dc34e1b19238.png)

**Comment by Greatone123** [comment]
I'm having the same issue, tank shows full, then when I leave and come back all tanks are at 32000.

**Comment by Indemnity83** [comment]
So, I fixed #1 which feels very similar. Then I refactored a whole bunch of code and looking back I'm wondering if I re-introduced the bug on by trying to set the capacity on instantiation again https://github.com/Indemnity83/irontank/blob/master/src/main/java/com/indemnity83/irontank/tile/TileIronTank.java#L25

**Comment by Indemnity83** [comment]
Getting closer ... steps to reproduce
1. Place a tank down, fill it exactly (48 clicks with a bucket on a gold tank)
2. Log out and back in
3. NO ISSUE
4. Attempt to add more fluid ... nothing happens (as expected)
5. Log out and back in
6. Tank now shows 32 / 48 buckets

**Comment by Indemnity83** [comment]
I belive I have it fixed with commit 2c9bd4b. I'll leave the issue open for a bit to have people verify. Update your version to the 1.7.10-1.0.2.54-beta release here:

https://minecraft.curseforge.com/projects/iron-tanks/files/2336499
