### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by SFort** [Indemnity83/irontank#39]
Works great on clients crashes on server.
[Pastebin](https://pastebin.com/jKDLKqvf)
irontanks: 1.11.2-2.0.0

**Comment by Indemnity83** [comment]
Thanks @SFort this is a known, but undocumented (until now) issue. I haven't split out the sided items so the server is trying to render gui items (and thus, crashing). 

Thanks for reporting this. I'm still working through some rendering glitches in a local fork which includes this fix. Maybe I'll push it up with the rendering glitch just to fix the higher priority error.

**Comment by Indemnity83** [comment]
1.11.2-2.0.0.alpha-2 includes this PR. 

https://minecraft.curseforge.com/projects/iron-tanks/files/2468052
