### ISSUE TITLE
[1.12] Crash while crafting

### ISSUE THREAD

**Issue by MakerTim** [Indemnity83/irontank#47]
Don't know if this is server only thing,
but when i open my crafting table with the crafting guide (that green book) open
i crash :(

[crashreport]
https://pastebin.com/vVtNSGhT

**Comment by Indemnity83** [comment]
I haven't been able to reproduce this error; can you give me any steps or guidance to reproduce it?

**Comment by MakerTim** [comment]
can't reproduce either, since updated to latest forge

it was 4times that it happend
when someone joined and the autofillin
strange stuff
