### ISSUE TITLE
Remove dependency on BuildCraft

### ISSUE THREAD

**Issue by josephcsible** [Indemnity83/irontank#53]
I'd like to use this mod, but not BuildCraft. Would you accept a PR that removed the dependency and made this into a standalone mod?

**Comment by Indemnity83** [comment]
Have you looked into what it would take to do that? I would serious consider it if it didn't remove any of the features that currently exist.

**Comment by josephcsible** [comment]
I haven't looked into it yet (didn't want to waste the effort in case your answer was just "no", but I will now).

**Comment by josephcsible** [comment]
Oh wow. You're basically using all of BuildCraft's tank code for everything.

**Comment by Indemnity83** [comment]
Yeah...

**Comment by Indemnity83** [comment]
Looks like if you want Buildcraft like tanks without Buildcraft your best bet is [Charset Tanks](https://minecraft.curseforge.com/projects/charset-storage-tanks)
