### ISSUE TITLE
Right click on tanks crashes game!

### ISSUE THREAD

**Issue by 3Domse3** [Indemnity83/irontank#58]
When I rightclick on the obsidian tank when it contains liquid XP, my game crashes (MC 1.11.2, Forge 1.11.2-13.20.1.2386)

**Comment by Indemnity83** [comment]
Which mod is Liquid XP from?

And just for clarity; what did you expect to happen when you right clicked?

**Comment by Indemnity83** [comment]
Also important, what were you holding (if anything) when you right clicked.

**Comment by 3Domse3** [comment]
My hand was empty. I'm not shure which mod it belongs to but you can get it when XP is sucked in by a vucuum hopper of Open Blocks mod. Then, the liquid gets treated as every other liquid in pipes/tanks/storages etc. When you right click on a tank of Open Block which contains liquid XP, you get those levels added to your experience. I expected either an "inventory" to show information about the liquid, to get the XP as described above or nothing. But I did not expect a crash ;)

**Comment by 3Domse3** [comment]
I did not try what happens with other liquids. Do your tanks have an inventory or an information GUI or are these just solid blocks with one purpose?

**Comment by Sempiternity87** [comment]
Is the liquid XP from Extra Utils maybe? Would probably need to look at the code for that liquid to see if it's doing anything special, or if it's the tank from Open Blocks that allows the "right-click, get levels."

**Comment by 3Domse3** [comment]
Nope. In JEI it says it is from Open Blocks.

**Comment by Indemnity83** [comment]
Can you provide the error (use pastebin or gist and provide a link please)

**Comment by Indemnity83** [comment]
@3Domse3 I assume you're still having this problem; can you include an error log? Either pastebin or gist link?

**Comment by 3Domse3** [comment]
I'm currently away from my PC. I'll try to send the log in the next days

**Comment by Indemnity83** [comment]
I actually realized (not sure how I missed this) that you were/are on Minecraft 1.11.2; the development on the mod for that branch had gone stagnant when 1.12.2 started so I'm working on back-porting the changes from 1.12.2 right now; that may make this issue moot.

**Comment by Indemnity83** [comment]
I pushed v2.0.0-beta.3 tonight; give that a try it should resolve your errors. If not, please let me know. 

As an FYI, this version unfortunately is incompatible with beta.2; it will not retain the tanks or upgrades in the world or your inventory when you install the new version. You'll get a notice from Minecraft about removing items from the world. 

[download](https://minecraft.curseforge.com/projects/iron-tanks/files/2546141)
[changelog](https://github.com/Indemnity83/irontanks/blob/support/1.11/CHANGELOG.md#200-beta3---2018-03-28)
