### ISSUE TITLE
Waila reports the wrong capacity when mixing tank types

### ISSUE THREAD

**Issue by Indemnity83** [Indemnity83/irontank#6]
If you have a tank stack with two dissimilar tank types (only tested with a normal Buildcraft tank and one of the tanks added by irontank) Waila will report the correct volume currently being stored, but reports the total storage capacity wrong (simply as 16 buckets \* the number of tanks in the stack).

**Comment by Indemnity83** [comment]
For future reference: WAILA tank capacity is calculated in [HUDHandlerBCTanks.java](https://bitbucket.org/ProfMobius/waila/src/41a40b4fee90488a76f25204d3bcea6e9984e4cd/src/main/java/mcp/mobius/waila/addons/buildcraft/HUDHandlerBCTanks.java?at=forge_1187&fileviewer=file-view-default#HUDHandlerBCTanks.java-54) in the buildcraft addon section

**Comment by Indemnity83** [comment]
Looks like this is being caused by a logic error in the BuildCraft TankTile class where it adds the capacity of the current tank when it meant to add the capacity of the bottom tank. 

Unfortunately, I don't see any elegant way to work around this problem so we're waiting on BuildCraft/BuildCraft#3046 to be merged to close this out.

**Comment by Indemnity83** [comment]
This has been addressed in BuildCraft/BuildCraft@9729576

**Comment by Indemnity83** [comment]
I'm leaving this issue open until the patch is released just in case anybody comes in looking to report the bug before its released upstream.

**Comment by asiekierka** [comment]
Pushed in BC 7.1.6.
