### ISSUE TITLE
Mod crash by loading

### ISSUE THREAD

**Issue by Zwiebel1954** [Indemnity83/irontank#62]

**Comment by Zwiebel1954** [comment]
Hi,
I play MC V 1.12.2 with forge 14.23.5.2768
By loading the game crash. Also when no other mod is installed

**Comment by Zwiebel1954** [comment]
Sorry I close with while take the wrong button

**Comment by Indemnity83** [comment]
Can you provide a crash log? Please past it into a gist, or something and link it here.

**Comment by Indemnity83** [comment]
Also, you state that no other mods are installed; but Iron Tanks requires that you have Buildcraft installed. Please list the version of Buildcraft you're using.

**Comment by Indemnity83** [comment]
If this ever comes back up, please re-open with a crash log and mod list, but since it's now a couple of months stale I'm closing this as invalid.
